### ISSUE TITLE
News shortcode should accept feed as attributes

### ISSUE THREAD

**Issue by chasethenag420** [gios-asu/wordpress-news-kiosk-plugin#15]
Example shortcode

```
[kiosk-asu-news feed='153,178,358,40']
```

Code should accept parameters and call the feed file as below urls

https://asunews.asu.edu/taxonomy/term/153/all/feed
https://asunews.asu.edu/taxonomy/term/178/all/feed
https://asunews.asu.edu/taxonomy/term/358/all/feed
https://asunews.asu.edu/taxonomy/term/40/all/feed

**Comment by rraub** [comment]
In the future, try and remember when your committing to reference the issue(s) your fixing https://help.github.com/articles/closing-issues-via-commit-messages/  

The commit messages get added to this thread so you can easily see what code changes were made to fix an issue.
