### ISSUE TITLE
Get tests working for PHP

### ISSUE THREAD

**Issue by idmontie** [gios-asu/wordpress-news-kiosk-plugin#2]
- [ ] Write PHP Unit Tests
- [ ] Get 90%+ Code Coverage

**Comment by chasethenag420** [comment]
Where should I look for percentage of code coverage by unit testing?

**Comment by idmontie** [comment]
You have to run phpunit manually with the flag `--strict-coverage` from what I remember.  We have a private repo called "Project Health" that has an example of how to run PHPUnit with PHPCodeCoverage, as well as PHPDocs.  Look at `projecthealth.php`.
